In [1]:
import pandas as pd

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [2]:
url = "imports-85.csv"
col_names=['symboling','normalized-losses','fuel-type','aspiration','num-of-doors','body-style','drive-wheels','engine-location','wheel-base',
                                    'length','width','height','curb-weight','engine-type','num-of-cylinders','engine-size',
                                    'fuel-system','bore','stroke','compression-ratio','horsepower','peak-rpm','city-mpg','highway-mpg','price']

df_car = pd.read_csv(url,sep=',',names = col_names ,na_values="?",  header=None)

In [3]:
df_car.head(5)

   symboling  normalized-losses fuel-type aspiration num-of-doors   body-style drive-wheels engine-location  wheel-base  length  width  height  curb-weight engine-type num-of-cylinders  engine-size fuel-system  bore  stroke  compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg    price
0          3                NaN       gas        std          two  convertible          rwd           front        88.6   168.8   64.1    48.8         2548        dohc             four          130        mpfi  3.47    2.68                9.0       111.0    5000.0        21           27  13495.0
1          3                NaN       gas        std          two  convertible          rwd           front        88.6   168.8   64.1    48.8         2548        dohc             four          130        mpfi  3.47    2.68                9.0       111.0    5000.0        21           27  16500.0
2          1                NaN       gas        std          two    hatchback          rwd           front        94.5   171.2   65.5    52.4         2823        ohcv              six          152        mpfi  2.68    3.47                9.0       154.0    5000.0        19           26  16500.0
3          2              164.0       gas        std         four        sedan          fwd           front        99.8   176.6   66.2    54.3         2337         ohc             four          109        mpfi  3.19    3.40               10.0       102.0    5500.0        24           30  13950.0
4          2              164.0       gas        std         four        sedan          4wd           front        99.4   176.6   66.4    54.3         2824         ohc             five          136        mpfi  3.19    3.40                8.0       115.0    5500.0        18           22  17450.0

In [4]:
df_car.describe()

        symboling  normalized-losses  wheel-base      length       width      height  curb-weight  engine-size        bore      stroke  compression-ratio  horsepower     peak-rpm    city-mpg  highway-mpg         price
count  205.000000         164.000000  205.000000  205.000000  205.000000  205.000000   205.000000   205.000000  201.000000  201.000000         205.000000  203.000000   203.000000  205.000000   205.000000    201.000000
mean     0.834146         122.000000   98.756585  174.049268   65.907805   53.724878  2555.565854   126.907317    3.329751    3.255423          10.142537  104.256158  5125.369458   25.219512    30.751220  13207.129353
std      1.245307          35.442168    6.021776   12.337289    2.145204    2.443522   520.680204    41.642693    0.273539    0.316717           3.972040   39.714369   479.334560    6.542142     6.886443   7947.066342
min     -2.000000          65.000000   86.600000  141.100000   60.300000   47.800000  1488.000000    61.000000    2.540000    2.070000           7.000000   48.000000  4150.000000   13.000000    16.000000   5118.000000
25%      0.000000          94.000000   94.500000  166.300000   64.100000   52.000000  2145.000000    97.000000    3.150000    3.110000           8.600000   70.000000  4800.000000   19.000000    25.000000   7775.000000
50%      1.000000         115.000000   97.000000  173.200000   65.500000   54.100000  2414.000000   120.000000    3.310000    3.290000           9.000000   95.000000  5200.000000   24.000000    30.000000  10295.000000
75%      2.000000         150.000000  102.400000  183.100000   66.900000   55.500000  2935.000000   141.000000    3.590000    3.410000           9.400000  116.000000  5500.000000   30.000000    34.000000  16500.000000
max      3.000000         256.000000  120.900000  208.100000   72.300000   59.800000  4066.000000   326.000000    3.940000    4.170000          23.000000  288.000000  6600.000000   49.000000    54.000000  45400.000000

In [5]:
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    float64
 2   fuel-type          205 non-null    object
 3   aspiration         205 non-null    object
 4   num-of-doors       203 non-null    object
 5   body-style         205 non-null    object
 6   drive-wheels       205 non-null    object
 7   engine-location    205 non-null    object
 8   wheel-base         205 non-null    float64
 9   length             205 non-null    float64
 10  width              205 non-null    float64
 11  height             205 non-null    float64
 12  curb-weight        205 non-null    int64
 13  engine-type        205 non-null    object
 14  num-of-cylinders   205 non-null    object
 15  engine-size        205 non-null    int64
 16  fuel-system        205 non-null    object
 17  bore               201 non-null    float64
 18  stroke             201 non-null    float64
 19  compression-ratio  205 non-null    float64
 20  horsepower         203 non-null    float64
 21  peak-rpm           203 non-null    float64
 22  city-mpg           205 non-null    int64
 23  highway-mpg        205 non-null    int64
 24  price              201 non-null    float64
dtypes: float64(11), int64(5), object(9)
memory usage: 40.2+ KB

In [6]:
df_car.columns

Index(['symboling', 'normalized-losses', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price'], dtype='object')

In [7]:
## Encoding ordinal features
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    float64
 2   fuel-type          205 non-null    object
 3   aspiration         205 non-null    object
 4   num-of-doors       203 non-null    object
 5   body-style         205 non-null    object
 6   drive-wheels       205 non-null    object
 7   engine-location    205 non-null    object
 8   wheel-base         205 non-null    float64
 9   length             205 non-null    float64
 10  width              205 non-null    float64
 11  height             205 non-null    float64
 12  curb-weight        205 non-null    int64
 13  engine-type        205 non-null    object
 14  num-of-cylinders   205 non-null    object
 15  engine-size        205 non-null    int64
 16  fuel-system        205 non-null    object
 17  bore               201 non-null    float64
 18  stroke             201 non-null    float64
 19  compression-ratio  205 non-null    float64
 20  horsepower         203 non-null    float64
 21  peak-rpm           203 non-null    float64
 22  city-mpg           205 non-null    int64
 23  highway-mpg        205 non-null    int64
 24  price              201 non-null    float64
dtypes: float64(11), int64(5), object(9)
memory usage: 40.2+ KB

In [8]:
df_car['num-of-doors'].value_counts()

four    114
two      89
Name: num-of-doors, dtype: int64

In [10]:
door_mapper = {"two": 2,
              "four": 4}

In [11]:
df_car['doors'] = df_car["num-of-doors"].replace(door_mapper)

In [9]:
df_car['num-of-cylinders'].value_counts()

four      159
six        24
five       11
eight       5
two         4
three       1
twelve      1
Name: num-of-cylinders, dtype: int64

In [12]:
cylinder_mapper = {"two":2,
                  "three":3,
                  "four":4,
                  "five":5,
                  "six":6,
                  "eight":8,
                  "twelve":12}

In [13]:
df_car['cylinders'] = df_car['num-of-cylinders'].replace(cylinder_mapper)

In [14]:
df_car.head()

   symboling  normalized-losses fuel-type aspiration num-of-doors   body-style drive-wheels engine-location  wheel-base  length  width  height  curb-weight engine-type num-of-cylinders  engine-size fuel-system  bore  stroke  compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg    price  doors  cylinders
0          3                NaN       gas        std          two  convertible          rwd           front        88.6   168.8   64.1    48.8         2548        dohc             four          130        mpfi  3.47    2.68                9.0       111.0    5000.0        21           27  13495.0    2.0          4
1          3                NaN       gas        std          two  convertible          rwd           front        88.6   168.8   64.1    48.8         2548        dohc             four          130        mpfi  3.47    2.68                9.0       111.0    5000.0        21           27  16500.0    2.0          4
2          1                NaN       gas        std          two    hatchback          rwd           front        94.5   171.2   65.5    52.4         2823        ohcv              six          152        mpfi  2.68    3.47                9.0       154.0    5000.0        19           26  16500.0    2.0          6
3          2              164.0       gas        std         four        sedan          fwd           front        99.8   176.6   66.2    54.3         2337         ohc             four          109        mpfi  3.19    3.40               10.0       102.0    5500.0        24           30  13950.0    4.0          4
4          2              164.0       gas        std         four        sedan          4wd           front        99.4   176.6   66.4    54.3         2824         ohc             five          136        mpfi  3.19    3.40                8.0       115.0    5500.0        18           22  17450.0    4.0          5

In [15]:
# Encoding non-ordinal categorical data
df_car['drive-wheels'].value_counts()

fwd    120
rwd     76
4wd      9
Name: drive-wheels, dtype: int64

In [16]:
df_car = pd.get_dummies(df_car,columns=['drive-wheels'])

In [17]:
df_car.head()

   symboling  normalized-losses fuel-type aspiration num-of-doors   body-style engine-location  wheel-base  length  width  height  curb-weight engine-type num-of-cylinders  engine-size fuel-system  bore  stroke  compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg    price  doors  cylinders  drive-wheels_4wd  drive-wheels_fwd  drive-wheels_rwd
0          3                NaN       gas        std          two  convertible           front        88.6   168.8   64.1    48.8         2548        dohc             four          130        mpfi  3.47    2.68                9.0       111.0    5000.0        21           27  13495.0    2.0          4                 0                 0                 1
1          3                NaN       gas        std          two  convertible           front        88.6   168.8   64.1    48.8         2548        dohc             four          130        mpfi  3.47    2.68                9.0       111.0    5000.0        21           27  16500.0    2.0          4                 0                 0                 1
2          1                NaN       gas        std          two    hatchback           front        94.5   171.2   65.5    52.4         2823        ohcv              six          152        mpfi  2.68    3.47                9.0       154.0    5000.0        19           26  16500.0    2.0          6                 0                 0                 1
3          2              164.0       gas        std         four        sedan           front        99.8   176.6   66.2    54.3         2337         ohc             four          109        mpfi  3.19    3.40               10.0       102.0    5500.0        24           30  13950.0    4.0          4                 0                 1                 0
4          2              164.0       gas        std         four        sedan           front        99.4   176.6   66.4    54.3         2824         ohc             five          136        mpfi  3.19    3.40                8.0       115.0    5500.0        18           22  17450.0    4.0          5                 1                 0                 0